---
title: "Melbourne Pedestrian Analysis"
author: "Andre Luiz Cunha"
date: "02/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Introduction

The title is "*Measuring the temporal and spatial impact of events on pedestrian flows*". The capstone project has been developed in University of Melbourne (UoM), Melbourne School of Engineering (MSE), Department of Infrastructure Engineering (IE) and it is composed by the team:

- Jessica Tong
- Hans Gao
- Marcus Rzanovski
- prof. Patricia Sauvieri
- prof. Andre Luiz Cunha


## 2. Dataset

The dataset was obtained on [City of Melbourne - Pedestrian Counting System](http://www.pedestrian.melbourne.vic.gov.au/). The data is from pedestrian counting system (loop sensor) and it contains hourly counts from 2009 to 2019. 

## 3. Method
The proposed method is evaluate methods to automatically detect events occured in the city, understand the event behavior in terms of time and space.

### Time domain
For time domain was used Wavelet Transform to detect the events and figure out the total time that each event affect the city.

### Space domain
In space domain the objective is identify the spread of the each type of event.

## 4. Daily report

### 21-07-2020
- [ ] Code function to open pedestrian data
- [ ] There is some error with sunlight, correct them on dataset
- [ ] Time domain analysis
- [ ] Wavelet analysis
- [ ] Spatio analysis